export const GET_MOVIES = "GET_MOVIES";

export const GET_MOVIE = "GET_MOVIE";

export const GET_HOLLYWOOD_MOVIES = "GET_HOLLYWOOD_MOVIES";

export const GET_BOLLYWOOD_MOVIES = "GET_BOLLYWOOD_MOVIES";

export const GET_DUBBED_MOVIES = "GET_DUBBED_MOVIES";

export const GET_FEATURED_MOVIES = "GET_FEATURED_MOVIES";

export const GET_TV_SERIES = "GET_TV_SERIES";

export const MOVIES_LOADING = "MOVIES_LOADING";

export const GET_GENRE_MOVIES = "GET_GENRE_MOVIES";

export const GET_YEAR_MOVIES = "GET_YEAR_MOVIES";

export const REQUEST_MOVIE = "REQUEST_MOVIE";

export const ALL_MOVIES_REQUESTS = "ALL_MOVIES_REQUESTS";

export const RECENTLY_UPLOADED_MOVIES = "RECENTLY_UPLOADED_MOVIES";

export const MOST_VIEWED = "MOST_VIEWED";

export const INCREMENT_VIEWS = "INCREMENT_VIEWS";

export const EMPTY_MOVIE = "EMPTY_MOVIE";

export const FEATURED_MOVIES = "FEATURED_MOVIES";
